In [1]:
a  = [2,4,6,8,10]

In [2]:
b = []
for num in a:
    b.append(2*num)
b

[4, 8, 12, 16, 20]

In [3]:
import numpy as np


In [4]:
a = np.array([1,2,3,4,5,6])

In [5]:
type(a)

numpy.ndarray

In [6]:
2*a

array([ 2,  4,  6,  8, 10, 12])

In [7]:
data = np.random.randn(2, 3)
data

array([[ 0.34814851, -0.29836458, -0.00281762],
       [ 0.77539686,  0.06691991,  0.56779392]])

In [8]:
data1 = np.arange(10)

In [9]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
data1.ndim

1

In [12]:
data.ndim

2

In [13]:
data.shape

(2, 3)

In [28]:
b= np.array([[100]])

In [29]:
b.ndim

2

In [30]:
b.shape

(1, 1)

In [31]:
_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [32]:
_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
threeD = np.arange(64).reshape(4,4,4)

In [34]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [37]:
threeD = np.arange(30).reshape(2,5,3)

In [38]:
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [39]:
threeD.ndim

3

In [40]:
m1 = np.arange(12).reshape(4,3)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,2]])

In [41]:
m1.shape == m2.shape

True

In [42]:
m1-m2

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [ 5,  7,  9]])

In [43]:
m1+m2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [13, 13, 13]])

In [44]:
m1/m2

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889],
       [2.25      , 3.33333333, 5.5       ]])

In [45]:
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [46]:
m1.shape

(4, 3)

In [47]:
m2.shape

(4, 3)

In [50]:
m3 = np.arange(12).reshape(3,4)

In [51]:
m3.shape

(3, 4)

In [56]:
m1*m2

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72],
       [36, 30, 22]])

In [58]:
print(m1.shape)
print(m3.shape)
m1@m3

(4, 3)
(3, 4)


array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [59]:
np.dot(m1,m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [60]:
m1.dot(m3)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [67]:
a  =np.array([33,44,66],dtype="float32")

In [68]:
a

array([33., 44., 66.], dtype=float32)

In [69]:
a  =np.array([33,44,66],dtype=np.float32)

In [70]:
a

array([33., 44., 66.], dtype=float32)

In [79]:
b = np.asarray(a,"int32")

In [80]:
b

array([33, 44, 66], dtype=int32)

In [83]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [84]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.empty(6)

array([0.34814851, 0.29836458, 0.00281762, 0.77539686, 0.06691991,
       0.56779392])

In [86]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [88]:
baaaaa = np.full((3,4),7)

In [89]:
baaaaa

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [90]:
jaaa=np.ones_like(baaaaa)

In [91]:
jaaa

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [92]:
alist = [1,2,3,4,5,6,7,8]

In [93]:
alist[4]

5

In [96]:
type(alist[2:4])

list

In [97]:
td = np.arange(36).reshape(6,6)

In [98]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [101]:
#td[r,c]
#td[--, --]
a=td[2:5,2:4]

array([[14, 15],
       [20, 21],
       [26, 27]])

In [100]:
td[2][3]

15

In [102]:
td

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])