<a href="https://colab.research.google.com/github/Sameer-Ahmed7/Deep_learning_Practice/blob/TitanicML/TitanicMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!pip install tensorflow --upgrade      

In [0]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
tf.__version__

'2.1.0'

# Prepared Test data

In [0]:
dfTest = pd.read_csv("test.csv")

In [5]:
dfTest.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [6]:
dfTest.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [7]:
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [8]:
dfTest.Age

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ... 
413     NaN
414    39.0
415    38.5
416     NaN
417     NaN
Name: Age, Length: 418, dtype: float64

In [0]:
AgeMeanTest = dfTest.Age.mean()

In [10]:
AgeMeanTest

30.272590361445783

In [0]:
dfTest.Age.fillna(AgeMeanTest,inplace=True)

In [12]:
dfTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            418 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [13]:
dfTest.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [0]:
dfTest.drop(["PassengerId","Pclass","Name","SibSp","Parch","Ticket","Fare","Cabin","Embarked"],axis=1,inplace=True)

In [15]:
dfTest.head()

Sex   Age
0    male  34.5
1  female  47.0
2    male  62.0
3    male  27.0
4  female  22.0

In [0]:
dfTest.Age = dfTest.Age.astype("int64")

In [17]:
dfTest.head()

Sex  Age
0    male   34
1  female   47
2    male   62
3    male   27
4  female   22

In [0]:
df1 = pd.get_dummies(dfTest.Sex)

In [19]:
df1

female  male
0         0     1
1         1     0
2         0     1
3         0     1
4         1     0
..      ...   ...
413       0     1
414       1     0
415       0     1
416       0     1
417       0     1

[418 rows x 2 columns]

In [0]:
test_x = pd.concat([dfTest,df1],axis=1)

In [21]:
test_x.head(2)

Sex  Age  female  male
0    male   34       0     1
1  female   47       1     0

In [0]:
test_x.drop(['Sex'],axis=1,inplace=True)

In [23]:
test_x.head(2)

Age  female  male
0   34       0     1
1   47       1     0

In [0]:
test_x = test_x.values

In [25]:
test_x

array([[34,  0,  1],
       [47,  1,  0],
       [62,  0,  1],
       ...,
       [38,  0,  1],
       [30,  0,  1],
       [30,  0,  1]])

# Prepare Train Data Set

In [0]:
dfTrain = pd.read_csv("train.csv")

In [27]:
dfTrain.shape

(891, 12)

In [28]:
dfTrain.head(2)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [29]:
dfTrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [30]:
dfTrain.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

In [0]:
meanTrain = dfTrain.Age.mean()

In [0]:
dfTrain.Age.fillna(meanTrain,inplace=True)

In [33]:
dfTrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [0]:
dfTrain.drop(["PassengerId","Pclass","Name","SibSp","Parch","Ticket","Fare","Cabin","Embarked"],axis=1,inplace=True)

In [35]:
dfTrain.head()

Survived     Sex   Age
0         0    male  22.0
1         1  female  38.0
2         1  female  26.0
3         1  female  35.0
4         0    male  35.0

In [36]:
dfTrain.shape

(891, 3)

In [0]:
dfTrain.Age = dfTrain.Age.astype("int64")

In [38]:
dfTrain.dtypes

Survived     int64
Sex         object
Age          int64
dtype: object

In [0]:
df3 = dfTrain.iloc[:,1:]

In [0]:
df4 = pd.get_dummies(df3.Sex)

In [0]:
train_x = pd.concat([df3,df4],axis=1)

In [0]:
train_x.drop(["Sex"],axis=1,inplace=True)

In [43]:
train_x.head(2)

Age  female  male
0   22       0     1
1   38       1     0

In [0]:
train_x = train_x.values

In [45]:
train_x

array([[22,  0,  1],
       [38,  1,  0],
       [26,  1,  0],
       ...,
       [29,  1,  0],
       [26,  0,  1],
       [32,  0,  1]])

In [0]:
train_y = dfTrain.iloc[:,0]

In [47]:
train_y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [48]:
train_x.shape,train_y.shape

((891, 3), (891,))

In [49]:
test_x.shape

(418, 3)

# Create Model

In [0]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [0]:
def build_model():
  model = models.Sequential()
  model.add(layers.Dense(100,input_dim = 3,activation="relu"))
  model.add(layers.Dense(1,activation="sigmoid"))
  model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [0]:
model = build_model()

In [53]:
model

In [54]:
print(type(train_x))

<class 'numpy.ndarray'>


In [0]:
train_x = train_x.astype("int64")

In [0]:
train_y = np.asarray(train_y)

In [0]:
train_y = train_y.astype("int64")

In [58]:
print(type(train_y))

<class 'numpy.ndarray'>


In [59]:
train_x,train_y

(array([[22,  0,  1],
        [38,  1,  0],
        [26,  1,  0],
        ...,
        [29,  1,  0],
        [26,  0,  1],
        [32,  0,  1]]),
 array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0

In [60]:
'''from tensorflow.keras.utils import to_categorical
train_y = to_categorical(train_y)'''

'from tensorflow.keras.utils import to_categorical\ntrain_y = to_categorical(train_y)'

In [61]:
print(train_y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [62]:
train_y.shape

(891,)

In [0]:
#train_y.reshape(1,891)

In [64]:
'''from keras.utils import to_categorical
df5 = to_categorical(train_x[:,0])'''

'from keras.utils import to_categorical\ndf5 = to_categorical(train_x[:,0])'

In [65]:
'''df5 = df5.astype('int64')'''

"df5 = df5.astype('int64')"

In [0]:
#df5

In [0]:
#df6 = train_x[:,0]

# Model Fit

In [68]:
model.fit(train_x , train_y,epochs=200,batch_size=10)

Train on 891 samples
Epoch 1/200
891/891 [==============================] - 1s 646us/sample - loss: 0.6155 - accuracy: 0.6857
Epoch 2/200
891/891 [==============================] - 0s 229us/sample - loss: 0.5495 - accuracy: 0.7688
Epoch 3/200
891/891 [==============================] - 0s 223us/sample - loss: 0.5311 - accuracy: 0.7800
Epoch 4/200
891/891 [==============================] - 0s 234us/sample - loss: 0.5235 - accuracy: 0.7890
Epoch 5/200
891/891 [==============================] - 0s 227us/sample - loss: 0.5218 - accuracy: 0.7890
Epoch 6/200
891/891 [==============================] - 0s 247us/sample - loss: 0.5174 - accuracy: 0.7890
Epoch 7/200
891/891 [==============================] - 0s 296us/sample - loss: 0.5104 - accuracy: 0.7935
Epoch 8/200
891/891 [==============================] - 0s 234us/sample - loss: 0.5137 - accuracy: 0.7912
Epoch 9/200
891/891 [==============================] - 0s 279us/sample - loss: 0.5083 - accuracy: 0.7935
Epoch 10/200
891/891 [============

# Model Save

In [0]:
model.save('my_titanic_model.h5')

In [0]:
#new_model = tf.keras.models.load_model('my_model.h5')
#new model load

# Model Load

In [0]:
new_model = tf.keras.models.load_model('my_titanic_model.h5')

In [0]:
test_y = pd.read_csv("gender_submission.csv")
test_y = test_y.Survived.values.reshape(418,)

# Evaluate Test Dataset

In [90]:
test_loss , test_acc = model.evaluate(test_x,test_y)
print("Test accuracy = ",test_acc)

418/418 [==============================] - 0s 214us/sample - loss: 0.2928 - accuracy: 0.9856
Test accuracy =  0.98564595


In [91]:
test_y.shape, train_y.shape

((418,), (891,))

# Predict Test DataSet

In [0]:
prediction = model.predict(test_x)

In [0]:
pred = []
for i in range(len(prediction)):
  if prediction[i]>0.5:
    a = 1
  else:
    a = 0
  pred.append(a)     

In [0]:
preddf = pd.DataFrame({"Survived":pred})

In [114]:
preddf.head()

Survived
0         0
1         1
2         0
3         0
4         1