In [1]:
import numpy as np

# Broadcasting

In [2]:
x = np.array([[1,2,3]])   #(1,3)
y = np.array([[4],[5]])  #(2,1)

In [3]:
x, y =np.broadcast_arrays(x, y)

In [4]:
x

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [6]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])

Pandas 

In [7]:
import pandas as pd

# Pandas Data Structures
Series
DataFrame

####### Series ###########

In [8]:
s1 = pd.Series([11,22,33,44,55,66,77,88,99,10])

In [9]:
s1  # pandas Series object

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
9    10
dtype: int64

In [10]:
# index (0-9 default index given bhy series object)

In [11]:
s1[9]  # ACCESSING value by index

10

In [12]:
s1[[9,2,4,5,6]]  # accessing multiple values 

9    10
2    33
4    55
5    66
6    77
dtype: int64

In [13]:
s1[5]=5555  # modifying a value in s series
s1[[2,3,4,5]]=[2222,3333,4444,55555]

In [14]:
s1

0       11
1       22
2     2222
3     3333
4     4444
5    55555
6       77
7       88
8       99
9       10
dtype: int64

In [15]:
#del s1[4]  # deleting a value in series 
del s1[2]

In [16]:
s1

0       11
1       22
3     3333
4     4444
5    55555
6       77
7       88
8       99
9       10
dtype: int64

In [17]:
s1[99]=999    # insert in a series with a new index 
s1

0        11
1        22
3      3333
4      4444
5     55555
6        77
7        88
8        99
9        10
99      999
dtype: int64

# Definig our own idexes

In [18]:
s2 = pd.Series([10,20,30,40], index=["oranges","apples","bananas","Kwi"])

In [19]:
s2

oranges    10
apples     20
bananas    30
Kwi        40
dtype: int64

In [20]:
s2.index

Index(['oranges', 'apples', 'bananas', 'Kwi'], dtype='object')

In [21]:
s2.values

array([10, 20, 30, 40], dtype=int64)

In [22]:
ourIndex=["oranges","apples","bananas","Kwi"]


s2 = pd.Series([10,20,30,40], index=ourIndex)

In [23]:
s2

oranges    10
apples     20
bananas    30
Kwi        40
dtype: int64

In [24]:
s2[s2<30]

oranges    10
apples     20
dtype: int64

In [25]:
'peech' in s2    # checking if required key is in Series or not

False

In [26]:
'oranges' in s2 # checking if required key is in Series or not

True

# Creating a series by using a dictionary

In [27]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
data = pd.Series(sdata)
data

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

data1 = pd.Series(sdata, index=states) 
data1

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
data1.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
data1.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
data1['California']=55000

In [32]:
data1

California    55000.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

# Data Frames

In [33]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year':  [2000, 2001, 2002, 2001, 2002, 2003],
        'pop':   [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]        }
df1  = pd.DataFrame(data)
df1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [34]:
type(df1)

pandas.core.frame.DataFrame

In [35]:
df1.shape

(6, 3)

In [36]:
df1['pop'] # selecting single columns by column header

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [37]:
df1[['pop', "year"]] # selecting multiple columns by column headers

pop  year
0  1.5  2000
1  1.7  2001
2  3.6  2002
3  2.4  2001
4  2.9  2002
5  3.2  2003

In [38]:
del df1["pop"] # deleting a column

In [39]:
df1

state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002
5  Nevada  2003

In [40]:
df1['debt']=100
df1

state  year  debt
0    Ohio  2000   100
1    Ohio  2001   100
2    Ohio  2002   100
3  Nevada  2001   100
4  Nevada  2002   100
5  Nevada  2003   100

In [41]:
df1["debt"]=[100,200,300,100,800,500]

In [42]:
df1

state  year  debt
0    Ohio  2000   100
1    Ohio  2001   200
2    Ohio  2002   300
3  Nevada  2001   100
4  Nevada  2002   800
5  Nevada  2003   500

In [43]:
df1['debt']=range(6)

In [44]:
df1

state  year  debt
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4
5  Nevada  2003     5

In [45]:
df1['debt']=df1['state']

In [46]:
df1

state  year    debt
0    Ohio  2000    Ohio
1    Ohio  2001    Ohio
2    Ohio  2002    Ohio
3  Nevada  2001  Nevada
4  Nevada  2002  Nevada
5  Nevada  2003  Nevada

In [70]:
dic  = {
       "Ai for EO":[78,89,68,90,87,86,67,49],
       "Python1":[40,78,87,49,88,78,76,75,],
       "Python2":[59,78,87,38,10,98,81,83]
      }

df = pd.DataFrame(dic, index=["Nasir", "Asad","Ramsha", 
                              "Mansoor","Saba","Saba",
                              "Hina","Ali"])
df

Ai for EO  Python1  Python2
Nasir           78       40       59
Asad            89       78       78
Ramsha          68       87       87
Mansoor         90       49       38
Saba            87       88       10
Saba            86       78       98
Hina            67       76       81
Ali             49       75       83

In [71]:
df['Total']=df['Ai for EO'] + df['Python1'] + df['Python2']

In [72]:
df

Ai for EO  Python1  Python2  Total
Nasir           78       40       59    177
Asad            89       78       78    245
Ramsha          68       87       87    242
Mansoor         90       49       38    177
Saba            87       88       10    185
Saba            86       78       98    262
Hina            67       76       81    224
Ali             49       75       83    207

In [81]:
#df['Status1']=[ "Fail" if totalNum<200  else "Pass" for totalNum in df["Total"]]
df['status']=["Fail" if nums<200  else "Pass" for nums in df['Ai for EO'],df['Python1'],df["Python2"]].values]

AttributeError: 'list' object has no attribute 'values'

In [84]:
df['status']=np.where(((df['Ai for EO']<50) & (df['Python1']<50) & (df["Python2"]<50)),"Fail","Pass")

In [86]:
a= 10
b=20

np.where(b>a, "Pass","fail")

array('Pass', dtype='<U4')

In [75]:
df['status']=["Pass" if a >= 33 and p1 >= 33 and p2 >= 33 else "Fails"
              for a,p1,p2 in zip(df['Ai for EO'],df['Python1'],df['Python2'])]
df

Ai for EO  Python1  Python2  Total Status1 status
Nasir           78       40       59    177    Fail   Pass
Asad            89       78       78    245    Pass   Pass
Ramsha          68       87       87    242    Pass   Pass
Mansoor         90       49       38    177    Fail   Pass
Saba            87       88       10    185    Fail  Fails
Saba            86       78       98    262    Pass   Pass
Hina            67       76       81    224    Pass   Pass
Ali             49       75       83    207    Pass   Pass

In [52]:
numbers= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
evenArr = []
oddArr = []
for num in numbers:
    if num%2==0:
        evenArr.append(num)
    else:
        oddArr.append(num)
print("Evens>>", evenArr)
print("Odds>>>", oddArr)

Evens>> [2, 4, 6, 8, 10, 12, 14]
Odds>>> [1, 3, 5, 7, 9, 11, 13, 15]


In [53]:
[num for num in numbers ]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [54]:
a = list(range(5))
b = list(range(6,11))
a

[0, 1, 2, 3, 4]

In [55]:
b

[6, 7, 8, 9, 10]

In [56]:
c = zip(a,b)
for i in c:
    print(i)

(0, 6)
(1, 7)
(2, 8)
(3, 9)
(4, 10)


In [57]:
df['Ai for EO']

Nasir      78
Asad       89
Ramsha     68
Mansoor    90
Saba       87
Saba       86
Hina       67
Ali        49
Name: Ai for EO, dtype: int64

In [58]:
df.head()

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails

In [59]:
df.tail()

Ai for EO  Python1  Python2  Total status
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass
Hina            67       76       81    224   Pass
Ali             49       75       83    207   Pass

In [60]:
df.loc['Nasir':'Hina']

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass
Hina            67       76       81    224   Pass

In [61]:
df.iloc[0:6]

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass

In [62]:
df.loc['Hina'::-1]

Ai for EO  Python1  Python2  Total status
Hina            67       76       81    224   Pass
Saba            86       78       98    262   Pass
Saba            87       88       10    185  Fails
Mansoor         90       49       38    177   Pass
Ramsha          68       87       87    242   Pass
Asad            89       78       78    245   Pass
Nasir           78       40       59    177   Pass

In [63]:
df.iloc[::-1]

Ai for EO  Python1  Python2  Total status
Ali             49       75       83    207   Pass
Hina            67       76       81    224   Pass
Saba            86       78       98    262   Pass
Saba            87       88       10    185  Fails
Mansoor         90       49       38    177   Pass
Ramsha          68       87       87    242   Pass
Asad            89       78       78    245   Pass
Nasir           78       40       59    177   Pass

In [64]:
df.loc['abc'] = [1,2,3,4,5]

In [65]:
df

Ai for EO  Python1  Python2  Total status
Nasir           78       40       59    177   Pass
Asad            89       78       78    245   Pass
Ramsha          68       87       87    242   Pass
Mansoor         90       49       38    177   Pass
Saba            87       88       10    185  Fails
Saba            86       78       98    262   Pass
Hina            67       76       81    224   Pass
Ali             49       75       83    207   Pass
abc              1        2        3      4      5

# 13-10-2019


In [88]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
         'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop':   [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [89]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [96]:
frame = pd.DataFrame(data, columns=['year', 'state', 'pop'])
frame

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [100]:
frame = pd.DataFrame(data, columns=['year', 'state', 'pop','Debt'], index = ["one","two","three","four","five","six"])


year   state  pop Debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [101]:
frame.columns

Index(['year', 'state', 'pop', 'Debt'], dtype='object')

In [102]:
frame.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [104]:
frame.loc["one"]

year     2000
state    Ohio
pop       1.5
Debt      NaN
Name: one, dtype: object

In [105]:
frame

year   state  pop Debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [106]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [107]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [108]:
frame.Debt=val

In [109]:
frame

year   state  pop  Debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [110]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)

In [112]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [113]:
pd.DataFrame(pop, index=[2001, 2002, 2003])    

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [114]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [115]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [117]:
pdata = pd.DataFrame(pdata)
pdata

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [118]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [119]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [120]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

# 5.2 Essential Functionality

In [121]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [122]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [123]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [124]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [125]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [126]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [127]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [237]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
          index=['a', 'c', 'd'],
          columns=['Ohio', 'Texas', 'California'])

In [238]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [239]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [240]:
states = ['Texas', 'Utah', 'California']
frame2.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [241]:
frame2.reindex(index=['f','b','a','d','c'],columns=['Texas', 'NewYork', 'Utah', 'California'])

Texas  NewYork  Utah  California
f    NaN      NaN   NaN         NaN
b    NaN      NaN   NaN         NaN
a    1.0      NaN   NaN         2.0
d    7.0      NaN   NaN         8.0
c    4.0      NaN   NaN         5.0

In [242]:
data = pd.DataFrame(np.arange(1,101).reshape((20,5)), 
                    columns=['a','b','c','d','e'],
                    index=range(1,101,5))
data

a   b   c   d    e
1    1   2   3   4    5
6    6   7   8   9   10
11  11  12  13  14   15
16  16  17  18  19   20
21  21  22  23  24   25
26  26  27  28  29   30
31  31  32  33  34   35
36  36  37  38  39   40
41  41  42  43  44   45
46  46  47  48  49   50
51  51  52  53  54   55
56  56  57  58  59   60
61  61  62  63  64   65
66  66  67  68  69   70
71  71  72  73  74   75
76  76  77  78  79   80
81  81  82  83  84   85
86  86  87  88  89   90
91  91  92  93  94   95
96  96  97  98  99  100

In [243]:
data = pd.DataFrame(np.arange(1,101).reshape((20,5)), 
                    columns=list('abcde'),
                    index=range(1,101,5))
data

a   b   c   d    e
1    1   2   3   4    5
6    6   7   8   9   10
11  11  12  13  14   15
16  16  17  18  19   20
21  21  22  23  24   25
26  26  27  28  29   30
31  31  32  33  34   35
36  36  37  38  39   40
41  41  42  43  44   45
46  46  47  48  49   50
51  51  52  53  54   55
56  56  57  58  59   60
61  61  62  63  64   65
66  66  67  68  69   70
71  71  72  73  74   75
76  76  77  78  79   80
81  81  82  83  84   85
86  86  87  88  89   90
91  91  92  93  94   95
96  96  97  98  99  100

In [244]:
list('abcde')

['a', 'b', 'c', 'd', 'e']

In [245]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [246]:
frame2.loc['c']

Ohio          3.0
Texas         4.0
California    5.0
Name: c, dtype: float64

In [247]:
frame2.loc[::-1]

Ohio  Texas  California
d   6.0    7.0         8.0
c   3.0    4.0         5.0
b   NaN    NaN         NaN
a   0.0    1.0         2.0

In [248]:
frame2.loc[::-1,::-1]

California  Texas  Ohio
d         8.0    7.0   6.0
c         5.0    4.0   3.0
b         NaN    NaN   NaN
a         2.0    1.0   0.0

In [249]:
frame2.iloc[::-1,::-1]

California  Texas  Ohio
d         8.0    7.0   6.0
c         5.0    4.0   3.0
b         NaN    NaN   NaN
a         2.0    1.0   0.0

In [250]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [251]:
frame2.loc['a':'c']

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0

In [252]:
frame2.iloc[0:3]

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0

In [254]:
frame2.loc['b'][0] = 3
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [260]:
frame2.loc['b'][[2,0]] = frame2.loc['b'][[0,2]]
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         3.0
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [256]:
frame2['Texas'][1] + 5

nan

In [261]:
frame4 = frame2.copy()
frame4['std'] = [4,5,7,8]
frame4

Ohio  Texas  California  std
a   0.0    1.0         2.0    4
b   NaN    NaN         3.0    5
c   3.0    4.0         5.0    7
d   6.0    7.0         8.0    8

In [262]:
frame2 + frame4

California  Ohio  Texas  std
a         4.0   0.0    2.0  NaN
b         6.0   NaN    NaN  NaN
c        10.0   6.0    8.0  NaN
d        16.0  12.0   14.0  NaN

In [266]:
abs(-67)

67

In [281]:
frame4.fillna(0, inplace=True)

In [279]:
frame4

Ohio  Texas  California  std
a   0.0    1.0         2.0    4
b   0.0    0.0         3.0    5
c   3.0    4.0         5.0    7
d   6.0    7.0         8.0    8

In [284]:
df = pd.read_csv('data.csv')
df.head()

Student Code  Degree     Student Name  Mid  Quiz 1  Quiz 2  \
0   022-14-19987  BS(CS)      Abdul Basit   28     8.0     3.0   
1  022-14-110233  BS(CS)      Adeel Ahmed   17     NaN     5.0   
2  022-14-110585  BS(CS)     Afrah Zareen   18     5.0     2.0   
3   022-14-19718  BS(CS)   Ahmed Ali Raza   14     7.0     2.0   
4  022-14-110648  BS(CS)  Ahsan Ali Vohra   27     7.0     6.0   

   Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0                8           7.0           9.0                    9   
1                5           8.0          10.0                   10   
2                5           8.0          10.0                   10   
3                7           NaN           2.0                    2   
4                7           7.0           9.0                    9   

   Total Sessional (50)  Final (50)  Total (100) Grade  
0                    45        25.0           70     B  
1                    32        18.0           50     F  
2                    33        30.0           63     C  
3                    23        23.0           46     F  
4                    43        34.0           77     B

In [290]:
df[df['Best of Quizzes'] > 7]

Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0   
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0   
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0   
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0   
9   022-14-110599  BS(CS)                         Arsalan   28     8.0   
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0   
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0   
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0   
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0   
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0   
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0   
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0   
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0   
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0   
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0   
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0   
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0   
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0   
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0   
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0   
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0   
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0   
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0   

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9   
5      6.0                9           8.0          10.0                   10   
7      6.0                9           8.0          10.0                   10   
8      4.0                9           7.0           9.0                    9   
9      6.0                8           8.0           NaN                    8   
10     7.0                8           8.0           NaN                    8   
11     5.0                8           5.0           NaN                    5   
13     4.0                8           8.0          10.0                   10   
17     5.0                8           9.0          11.0                   11   
19     6.0                9           8.0          10.0                   10   
21     6.0                9           9.0          11.0                   11   
25     6.0                9           8.0          10.0                   10   
27     6.0                8           8.0          10.0                   10   
30     6.0                8           9.0           NaN                    9   
34     6.0                9           8.0          10.0                   10   
35     5.0                8           NaN          10.0                   10   
36     5.0                9           9.0           NaN                    9   
37     5.0                9           9.0           NaN                    9   
40     6.0                9           8.0          10.0                   10   
43     4.0                9           6.0           8.0                    8   
45     6.0                9           9.0           NaN                    9   
46     5.0                8           8.0          10.0                   10   
47     5.0                9           5.0           7.0                    7   

    Total Sessional (50)  Final (50)  Total (100) Grade  
0                     45        25.0           70     B  
5                     44        27.0           71     B  
7                     45        40.0           85     A  
8                     37        24.0           61     C  
9                