In [10]:
a  = [1,2,3,4,5,6,7,8,9,10]

In [11]:

%time
b = []

for num in a:
    b.append(num*5)


Wall time: 0 ns


In [12]:
import numpy as np

In [13]:
%time
a = np.array([1,2,3,4,5,6,7,8,9,10])

Wall time: 0 ns


In [14]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
numpyArray = np.array([22,44.5,55,66], dtype = np.int8)
print(type(numpyArray))
(numpyArray)


<class 'numpy.ndarray'>


array([22, 44, 55, 66], dtype=int8)

In [34]:
randomArray = np.random.randn(3)*100

In [35]:
randomArray

array([-64.78110088, -86.7828698 , 104.82466515])

In [36]:
randomArray.ndim

1

In [37]:
randomArray.shape

(3,)

In [38]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])

In [39]:
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [40]:
twoD.shape

(4, 3)

In [41]:
zeroD = np.array(100)

In [42]:
zeroD.ndim

0

In [43]:
zeroD.shape

()

In [47]:
miscD = np.array([[[[99]]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [49]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
flat = np.ravel(a)

In [59]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
z = np.array([22,33,44,55,66,77])

In [61]:
z

array([22, 33, 44, 55, 66, 77])

In [62]:
rZ = z.reshape(2,3)

In [64]:
rZ

array([[22, 33, 44],
       [55, 66, 77]])

In [67]:
fZ = np.ravel(rZ)

In [68]:
fZ

array([22, 33, 44, 55, 66, 77])

In [72]:
twoD = np.arange(36).reshape(6,6)

In [73]:
twoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [74]:
threeD = twoD.reshape(3,3,4)

In [75]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [76]:
rebacktwoD = threeD.reshape(6,6)

In [77]:
rebacktwoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,6,8],[8,7,6],[9,8,7]]])

In [79]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 6, 8],
        [8, 7, 6],
        [9, 8, 7]]])

In [81]:
twoD  + twoD

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [82]:
twoD  - twoD

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [83]:
twoD  / twoD

C:\Users\MT-2019\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [84]:
twoD * twoD

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [85]:
m1 = np.arange(12).reshape(4,3)

In [88]:
m2 = np.random.randn(16).reshape(4,4)

In [89]:
m1 + m2

ValueError: operands could not be broadcast together with shapes (4,3) (4,4) 

In [90]:
m3  = np.arange(18).reshape(3,6)

In [91]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [92]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
m1@m3

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [96]:
np.dot(m1,m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [97]:
m1.dot(m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [100]:
zeeeros = np.zeros(4,dtype = "int8")

In [101]:
zeeeros

array([0, 0, 0, 0], dtype=int8)

In [102]:
zeeeros = np.zeros((4,5),dtype = "int8")

In [103]:
zeeeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [108]:
onessssss = np.ones((5,5))

In [109]:
onessssss*50

array([[50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.]])

In [115]:
fullll = np.full((4,4),100)

In [117]:
fullll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [118]:
emptyyy = np.empty((4,4,4))

In [119]:
emptyyy

array([[[0.00000000e+000, 1.26557631e-311,             nan,
         0.00000000e+000],
        [6.95246748e-310, 7.90505033e-323, 1.26558996e-311,
         1.26556543e-311],
        [1.26553921e-311, 1.26556540e-311, 0.00000000e+000,
         1.26558974e-311],
        [0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
         0.00000000e+000]],

       [[2.31297541e-312, 0.00000000e+000, 7.55430502e-312,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [120]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [121]:
like = np.zeros_like(m3)

In [122]:
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [128]:
i = np.eye(5,5)

In [129]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [130]:
j  = i.astype("int")   # changes data type

In [131]:
j

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Basic Indexing and Slicing

In [132]:
aList = [99,77,55,33,11]

In [135]:
type(aList[0:3])

list

In [137]:
tDarray  = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [138]:
tDarray[3,2]

20

In [139]:
tDarray[3][2]

20

In [140]:
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [141]:
#tDarray[row,column]
#tDarray[start:end, start:end]
tDarray[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [142]:
tDarray[5:,3:4]

array([[33]])

In [143]:
tDarray[1:2,2:5]

array([[ 8,  9, 10]])