In [1]:
import numpy as np

In [5]:
arr1 = np.ones(12)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
arr1 = np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr2 = np.ones_like(arr1)
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr3 = np.arange(16).reshape(4,4)
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
arr3.ndim

1

In [16]:
arr3.shape = (8,2)
arr3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [17]:
arr3.resize(4,4)

In [18]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
arr3.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [20]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
arr4 = np.arange(10,501,10).reshape(10,5)

In [37]:
arr4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [38]:
arr5 = arr4[:5,:]
arr5

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [39]:
arr5 = arr5 * 2
arr5

array([[ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200],
       [220, 240, 260, 280, 300],
       [320, 340, 360, 380, 400],
       [420, 440, 460, 480, 500]])

In [40]:
arr4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [50]:
arr6 = arr4[[0,1,-2,-1],:2]
arr6

array([[ 10,  20],
       [ 60,  70],
       [410, 420],
       [460, 470]])

In [46]:
arr4

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [53]:
arr4[::-1,::-1]

array([[500, 490, 480, 470, 460],
       [450, 440, 430, 420, 410],
       [400, 390, 380, 370, 360],
       [350, 340, 330, 320, 310],
       [300, 290, 280, 270, 260],
       [250, 240, 230, 220, 210],
       [200, 190, 180, 170, 160],
       [150, 140, 130, 120, 110],
       [100,  90,  80,  70,  60],
       [ 50,  40,  30,  20,  10]])

In [63]:
np.vsplit(arr4,2)

[array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200],
        [210, 220, 230, 240, 250]]), array([[260, 270, 280, 290, 300],
        [310, 320, 330, 340, 350],
        [360, 370, 380, 390, 400],
        [410, 420, 430, 440, 450],
        [460, 470, 480, 490, 500]])]

In [62]:
arr6, arr7 = np.vsplit(arr4,2)

In [64]:
arr6

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [65]:
arr7

array([[260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [66]:
np.hstack((arr6,arr7))

array([[ 10,  20,  30,  40,  50, 260, 270, 280, 290, 300],
       [ 60,  70,  80,  90, 100, 310, 320, 330, 340, 350],
       [110, 120, 130, 140, 150, 360, 370, 380, 390, 400],
       [160, 170, 180, 190, 200, 410, 420, 430, 440, 450],
       [210, 220, 230, 240, 250, 460, 470, 480, 490, 500]])

In [67]:
np.vstack((arr6,arr7))

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250],
       [260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350],
       [360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450],
       [460, 470, 480, 490, 500]])

In [71]:
np.stack((arr6,arr7), axis=1)

array([[[ 10,  20,  30,  40,  50],
        [260, 270, 280, 290, 300]],

       [[ 60,  70,  80,  90, 100],
        [310, 320, 330, 340, 350]],

       [[110, 120, 130, 140, 150],
        [360, 370, 380, 390, 400]],

       [[160, 170, 180, 190, 200],
        [410, 420, 430, 440, 450]],

       [[210, 220, 230, 240, 250],
        [460, 470, 480, 490, 500]]])

In [75]:
np.vsplit(arr4,5)

[array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]), array([[110, 120, 130, 140, 150],
        [160, 170, 180, 190, 200]]), array([[210, 220, 230, 240, 250],
        [260, 270, 280, 290, 300]]), array([[310, 320, 330, 340, 350],
        [360, 370, 380, 390, 400]]), array([[410, 420, 430, 440, 450],
        [460, 470, 480, 490, 500]])]

In [77]:
np.hsplit(arr4,5)

[array([[ 10],
        [ 60],
        [110],
        [160],
        [210],
        [260],
        [310],
        [360],
        [410],
        [460]]), array([[ 20],
        [ 70],
        [120],
        [170],
        [220],
        [270],
        [320],
        [370],
        [420],
        [470]]), array([[ 30],
        [ 80],
        [130],
        [180],
        [230],
        [280],
        [330],
        [380],
        [430],
        [480]]), array([[ 40],
        [ 90],
        [140],
        [190],
        [240],
        [290],
        [340],
        [390],
        [440],
        [490]]), array([[ 50],
        [100],
        [150],
        [200],
        [250],
        [300],
        [350],
        [400],
        [450],
        [500]])]

In [78]:
arr3 = np.arange(1,25).reshape(2,3,4)
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [79]:
arr3[1][1][2]

19

In [80]:
arr3[1,1,2]

19

In [81]:
arr3[1,:2,1:-1]

array([[14, 15],
       [18, 19]])

In [82]:
arr3[0,-1,2:]

array([11, 12])

In [83]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [84]:
arr3[1,0::2,0:3:2]

array([[13, 15],
       [21, 23]])

In [85]:
arr3[1,[0,2],0:3:2]

array([[13, 15],
       [21, 23]])

In [86]:
arr4=np.arange(100).reshape(4,5,5)

In [87]:
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [90]:
arr4[2:,:,:]

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [91]:
import pandas as pd

In [92]:
from pandas import Series, DataFrame

In [94]:
obj = pd.Series([2,33,4,88,5,66,77])
obj

0     2
1    33
2     4
3    88
4     5
5    66
6    77
dtype: int64

In [95]:
type(obj)

pandas.core.series.Series

In [96]:
obj.values

array([ 2, 33,  4, 88,  5, 66, 77], dtype=int64)

In [97]:
obj.index

RangeIndex(start=0, stop=7, step=1)

In [105]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'a', 'a', 'c'])

In [106]:
obj2

d    4
a    7
a   -5
c    3
dtype: int64

In [107]:
obj2['a']

a    7
a   -5
dtype: int64

In [108]:
obj2['d'] = 6

In [109]:
obj2

d    6
a    7
a   -5
c    3
dtype: int64

In [110]:
obj2[['c', 'a', 'd']]

c    3
a    7
a   -5
d    6
dtype: int64

In [113]:
obj2[obj2>0]

d    6
a    7
c    3
dtype: int64

In [114]:
#Converting a dictionary in Series

In [135]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [136]:
sdata = pd.Series(sdata)

In [137]:
sdata

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [138]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [139]:
sdata = pd.Series(sdata, index=states)

In [140]:
sdata

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [141]:
pd.isnull(sdata)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [142]:
pd.notnull(sdata)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [143]:
sdata

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [144]:
sdata1 = sdata.copy()
sdata1

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [145]:
sdata1['California'], sdata1['Ohio'] = sdata1['Ohio'] , sdata1['California']
sdata1['Karachi'] = 10000
sdata1

California    35000.0
Ohio              NaN
Oregon        16000.0
Texas         71000.0
Karachi       10000.0
dtype: float64

In [146]:
sdata

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [147]:
sdata + sdata1

California         NaN
Karachi            NaN
Ohio               NaN
Oregon         32000.0
Texas         142000.0
dtype: float64

In [149]:
sdata.index = ['Ohio', 'Oregon', 'Texas', 'California']

In [150]:
sdata

Ohio              NaN
Oregon        35000.0
Texas         16000.0
California    71000.0
dtype: float64

In [187]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [191]:
frame.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [158]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [192]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [194]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])
frame2['debt'] = range(1,7)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     5
six    2003  Nevada  3.2     6

In [167]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [196]:
frame2.loc['one':'six':3]

year   state  pop  debt
one   2000    Ohio  1.5     1
four  2001  Nevada  2.4     4

In [179]:
frame2.iloc[0:2]

year state  pop  debt
one  2000  Ohio  1.5     1
two  2001  Ohio  1.7     2

In [198]:
val = pd.Series([-1.2, -1.5, -1.7, 7], index=['two', 'four', 'five', 'three'])
val

two     -1.2
four    -1.5
five    -1.7
three    7.0
dtype: float64

In [208]:
frame2['debt1'] = val
frame2

year   state  pop  debt  debt1
one    2000    Ohio  1.5     1    NaN
two    2001    Ohio  1.7     2   -1.2
three  2002    Ohio  3.6     3    7.0
four   2001  Nevada  2.4     4   -1.5
five   2002  Nevada  2.9     5   -1.7
six    2003  Nevada  3.2     6    NaN

In [209]:
frame2['debt1'][['six','one']] = 13,14
frame2

C:\Users\R9_PC2\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


year   state  pop  debt  debt1
one    2000    Ohio  1.5     1   14.0
two    2001    Ohio  1.7     2   -1.2
three  2002    Ohio  3.6     3    7.0
four   2001  Nevada  2.4     4   -1.5
five   2002  Nevada  2.9     5   -1.7
six    2003  Nevada  3.2     6   13.0

In [219]:
frame2['eastern'] = ["Pass" if i == "Ohio" else "Fail" for i in frame2.state ]
frame2

year   state  pop  debt  debt1 eastern
one    2000    Ohio  1.5     1   14.0    Pass
two    2001    Ohio  1.7     2   -1.2    Pass
three  2002    Ohio  3.6     3    7.0    Pass
four   2001  Nevada  2.4     4   -1.5    Fail
five   2002  Nevada  2.9     5   -1.7    Fail
six    2003  Nevada  3.2     6   13.0    Fail

In [227]:
data = {
    "Math": [90, 89, 78, 32, 76],
    "Physics": [23, 45, 78, 90, 34],
    "Chemistry": [32, 34, 67, 89, 88]
}
frame3 = pd.DataFrame(data, index=['std1','std2','std3','std4','std5'])
frame3

Math  Physics  Chemistry
std1    90       23         32
std2    89       45         34
std3    78       78         67
std4    32       90         89
std5    76       34         88

In [226]:
frame3['total'] = [m+p+c for m,p,c in zip(frame3['Math'],frame3['Physics'],frame3['Chemistry'])]
frame3['remarks'] = ["Pass" if m >= 33 and p >= 33 and c >= 33 else "Fail" for m,p,c in zip(frame3['Math'],frame3['Physics'],frame3['Chemistry'])]
frame3

Math  Physics  Chemistry  total remarks
0    90       23         32    145    Fail
1    89       45         34    168    Pass
2    78       78         67    223    Pass
3    32       90         89    211    Fail
4    76       34         88    198    Pass

In [229]:
arr4 = [1,2,3,4,5]

In [231]:
any()

TypeError: '>' not supported between instances of 'list' and 'int'