# Numpy 3D arrays

In [1]:
import numpy as np

d3 = np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

Indexing 3D

In [2]:
d3[1,2,1]

36

In [3]:
d3[1]

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [4]:
d3[0:,2:,1:3]

array([[[11, 12],
        [16, 17],
        [21, 22]],

       [[36, 37],
        [41, 42],
        [46, 47]]])

In [5]:
#d3[1:2,4:5,0:5]
d3[1:,4:,:]

array([[[45, 46, 47, 48, 49]]])

In [6]:
### d3[0:,2:4,1:3]

In [7]:
d3[1,:,3:4]

array([[28],
       [33],
       [38],
       [43],
       [48]])

# BroadCasting

In [8]:
x = np.array([[1,2,3]])  #(1,3)
y = np.array([[1],[2],[3]])#(3,1)
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [9]:
x.shape, y.shape

((1, 3), (3, 1))

In [10]:
x,y=np.broadcast_arrays(x,y)
x 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
y

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [12]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Pandas

# Pandas data structure
Series
DataFrame

# Series

In [13]:
import pandas as pd

In [14]:
s = pd.Series([111,222,333,444,555,666,777])
s  # pandas series object

0    111
1    222
2    333
3    444
4    555
5    666
6    777
dtype: int64

In [15]:
# labels/index and values

In [16]:
#getting a single series value

s[4]

555

In [17]:
#getting a single series value
s[[5,0,3,1]]

5    666
0    111
3    444
1    222
dtype: int64

In [18]:
# updating a series value
s[3]= 1000
# updating multiple series value

s[[2,4,0]]=[9999,7777,1111]

In [19]:
s

0    1111
1     222
2    9999
3    1000
4    7777
5     666
6     777
dtype: int64

In [20]:
# deleting a value in series

del s[4]
s

0    1111
1     222
2    9999
3    1000
5     666
6     777
dtype: int64

In [21]:
# deleting multiple values in a series
del s[[0,2,6]]

# not allowed

TypeError: '[0, 2, 6]' is an invalid key

In [ ]:
s[1234]= 45676878
s[[123,345,678]]=[23,23,23]
#not allowed

In [ ]:
s

In [ ]:
s1 = pd.Series([100,200,300,400], index=["apples", "oranges","bananas", "grapes"])

In [ ]:
s1

# Creating a series using a dictionary

In [ ]:
aDic = {"name":"Nasir Hussain", "Class":"AI", "Time":"5-9"}

In [ ]:
aDic

In [ ]:
s2 = pd.Series(aDic)
s2

In [ ]:
s3 = pd.Series(s1, index=["mango", "oranges","bananas", "grapes"])

In [ ]:
s3

In [ ]:
s3["mango"]=100

In [ ]:
s3

In [ ]:
s3.values

In [ ]:
s3.index

In [ ]:
s3[s3>200]

In [ ]:
s3>200

In [ ]:
"Mango" in s3

In [ ]:
s4= pd.Series(s3.values, index=[22,33,44,55])

In [ ]:
s4

In [ ]:
s3

In [ ]:
s3+s4

# DataFrame

In [ ]:
df = pd.DataFrame([123,234,345,456])
df

In [ ]:
df = pd.DataFrame(["Red","Green", "Blue"],index=['v1','v2','v3'])
df

In [ ]:
df = pd.DataFrame(["Red","Green", "Blue"],index=['v1','v2','v3'],columns=["Colors"])
df

# Creating a Data Frame from a dictionary

In [ ]:
score = {"Ai for EO":[76,78,89,90,83,82,87,89,90,99],
         "Python1"  :[67,78,76,75,89,90,54,78,87,45],
         "Python2"  :[78,76,79,56,34,89,45,78,91,89]
        }

In [ ]:
df = pd.DataFrame(score,index=["Nasir", "Asad","Ahmed",
                               "Abdullah","Faraz", "Zaid",
                               "Ali", "Khan", 'Faisal', 
                               "Fahad"])
df

In [ ]:
df.head(3)

In [ ]:
df.tail(3)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
#data = pd.read_csv("banknotes.csv")

In [ ]:
df['Python1']

In [ ]:
df['Ai for EO']

In [ ]:
df.loc[['Abdullah','Fahad']]['Python1']

In [ ]:
df

In [ ]:
df["extra"]=range(10)
df

In [ ]:
del df["extra"]
df

In [ ]:
df["Total"]=df["Ai for EO"] + df["Python1"] + df['Python2']
df

In [ ]:
# df["Status"]=np.where(df['Total']>200,"Pass","Fail")
# df



In [ ]:
df["Status"]=["Pass" if marks>200 else "Fails" for marks in df['Total']]

In [ ]:
df

In [ ]:
df['RevisedStatus']=np.where(((df['Ai for EO']>=50) & (df["Python1"]>=50) & (df["Python2"]>=50)),"Pass","Fail")

In [ ]:
df

In [ ]:
df['newStatus']=["Pass" if (ai>=50) & (p1>=50) & (p2>=50) else "Fail" for ai,p1,p2 in zip(df["Ai for EO"], df['Python1'],df["Python2"])]

In [ ]:
df

In [ ]:
x = [1,2,3,4]
y = ['a','b','c','d']
z = zip(x,y)


In [ ]:
for x,y in z:
    print(x,y)

# 13-10-2019

In [ ]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [ ]:
frame3 = pd.DataFrame(pop)

In [ ]:
frame3

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         
         'Nevada': frame3['Nevada'][:2]}
pdata = pd.DataFrame(pdata)
pdata

In [ ]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [ ]:
frame3

In [ ]:
frame3.values

# Index Objects

In [ ]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [ ]:
obj

In [ ]:
index = obj.index

In [ ]:
index

In [ ]:
index[1:]

# 5.2 Essential Functionality

In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [ ]:
obj

In [ ]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])


In [ ]:
obj2['e']=100
obj2

In [ ]:
bj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,  4,9])

In [ ]:
obj3

In [ ]:
obj3.reindex(range(6))

In [ ]:
obj3.reindex(range(6), method='ffill')

In [ ]:
obj3.reindex(range(6), method='bfill')

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])
frame

In [ ]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2


In [ ]:
states = ['Texas', 'Utah', 'California']

In [ ]:
frame.reindex(columns=states)

In [ ]:
newFrame = frame.reindex(index=['a', 'b', 'c', 'd'],
                        columns=['Texas', 'Utah', 'California',
                                 "NewYork"])
newFrame

In [ ]:
newFrame['NewYork']['b']=800

In [ ]:
newFrame

In [ ]:
frame.loc[['a', 'b', 'c', 'd'], states]

# Dropping Entries from an Axis

In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [ ]:
obj.drop('c',inplace=True)

In [ ]:
obj

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

In [ ]:
data.drop(['Colorado', 'Ohio'])

In [ ]:
data

In [ ]:
data.drop('two', axis=1)

In [ ]:
df = pd.read_csv('data.csv')

In [ ]:
df

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df[df['Mid']>20].count()

In [ ]:
df[(df['Mid']>20) & (df['Best of Quizzes']>7) & (df['Best of Assignments']>7)]

In [ ]:
df.info()

In [ ]:
df

In [ ]:
df1=df.copy()

In [ ]:



df1['Quiz 1'].fillna(df1['Quiz 1'].mean(),inplace=True)

In [ ]:
df1

In [ ]:
df.mean

# 19-10-2019

In [22]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                        index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.012089 -1.200073 -0.153862
Ohio    0.566259  1.158389 -0.315582
Texas   0.122091 -2.147560  0.661842
Oregon -0.604837  0.295723  1.576296

In [26]:
frame = np.abs(frame)
frame

b         d         e
Utah    0.012089  1.200073  0.153862
Ohio    0.566259  1.158389  0.315582
Texas   0.122091  2.147560  0.661842
Oregon  0.604837  0.295723  1.576296

In [28]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    0.592748
d    1.851836
e    1.422434
dtype: float64

In [29]:
frame.apply(f, axis='columns')

Utah      1.187984
Ohio      0.842807
Texas     2.025468
Oregon    1.280573
dtype: float64

# Sorting and Ranking

In [30]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [31]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [32]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])
frame


d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [33]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [34]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [35]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [36]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [48]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [1,2,3,4]})
frame

b  a
0  4  1
1  7  2
2 -3  3
3  2  4

In [49]:
frame.sort_values(by='b')

b  a
2 -3  3
3  2  4
0  4  1
1  7  2

In [50]:
frame

b  a
0  4  1
1  7  2
2 -3  3
3  2  4

In [52]:
frame.sort_values(by=['a', 'b'])

b  a
0  4  1
1  7  2
2 -3  3
3  2  4

In [61]:
obj = pd.Series([7, -5, 7, 4, 2, 4,0, 4,])
obj

0    7
1   -5
2    7
3    4
4    2
5    4
6    0
7    4
dtype: int64

In [62]:
obj.rank()

0    7.5
1    1.0
2    7.5
3    5.0
4    3.0
5    5.0
6    2.0
7    5.0
dtype: float64

In [56]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                    [np.nan, np.nan], [0.75, -1.3]],
                        index=['a', 'b', 'c', 'd'],
                            columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [57]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [58]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [60]:
df.mean(axis='columns', skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [67]:
frame = pd.DataFrame({'b': [1,0], 'a': [0,1]})


In [68]:
frame

b  a
0  1  0
1  0  1

In [65]:
frame.corr()

b    a
b  1.0 -1.0
a -1.0  1.0

In [66]:
frame.cov()

b    a
b  0.5 -0.5
a -0.5  0.5

In [69]:
frame

b  a
0  1  0
1  0  1

In [71]:
import pandas_datareader.data as web

In [72]:
all_data = {ticker: web.get_data_yahoo(ticker)
                    for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [75]:
all_data

{'AAPL':                   High         Low        Open       Close      Volume  \
 Date                                                                     
 2014-10-20   99.959999   98.220001   98.320000   99.760002  77517300.0   
 2014-10-21  103.019997  101.269997  103.019997  102.470001  94623900.0   
 2014-10-22  104.110001  102.599998  102.839996  102.989998  68263100.0   
 2014-10-23  105.050003  103.629997  104.080002  104.830002  71074700.0   
 2014-10-24  105.489998  104.529999  105.180000  105.220001  47053900.0   
 2014-10-27  105.480003  104.699997  104.849998  105.110001  34187700.0   
 2014-10-28  106.739998  105.349998  105.400002  106.739998  48060900.0   
 2014-10-29  107.370003  106.360001  106.650002  107.339996  52687900.0   
 2014-10-30  107.349998  105.900002  106.959999  106.980003  40654800.0   
 2014-10-31  108.040001  107.209999  108.010002  108.000000  44639300.0   
 2014-11-03  110.300003  108.010002  108.220001  109.400002  52282600.0   
 2014-11-04  109.

In [76]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})

In [77]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2014-10-20   91.539482  136.936264   39.458977   519.413940
2014-10-21   94.026176  132.182739   40.175110   525.098328
2014-10-22   94.503311  131.016617   39.727531   531.251465
2014-10-23   96.191689  131.332458   40.300430   542.490601
2014-10-24   96.549545  131.251480   41.294075   538.302063
2014-10-27   96.448616  131.081451   41.097130   539.289368
2014-10-28   97.944298  132.482391   41.616329   547.397095
2014-10-29   98.494850  132.369003   41.732697   547.825928
2014-10-30   98.164513  133.089706   41.222458   548.803284
2014-10-31   99.100471  133.130219   42.028111   557.549255
2014-11-03  100.385109  133.097809   42.466732   553.699829
2014-11-04   99.651047  131.713089   42.583115   552.592834
2014-11-05   99.889618  131.040939   42.842709   544.425293
2014-11-06  100.175293  131.644287   43.594646   540.555908
2014-11-07  100.460983  132.141617   43.576752   539.528748
2014-11-10  100.295105  133.299408   43.764729   545.990967
2014-11-11  101.096870  133.144485   43.746830   548.783325
2014-11-12  102.525322  132.019318   43.666264   545.811462
2014-11-13  103.972198  132.728683   44.409256   543.886780
2014-11-14  105.225540  133.845688   44.382393   542.909424
2014-11-17  105.050430  133.845688   44.274975   535.041016
2014-11-18  106.414368  131.994904   43.905632   533.565125
2014-11-19  105.677094  131.619797   43.437222   535.519714
2014-11-20  107.188477  130.975677   43.869606   533.365662
2014-11-21  107.335945  131.204025   43.221031   536.028320
2014-11-24  109.326523  132.206879   42.869705   537.793518
2014-11-25  108.377327  131.888885   42.761612   539.598511
2014-11-26  109.667534  132.043823   43.013840   538.890503
2014-11-28  109.603027  132.223190   43.067890   540.346497
2014-12-01  106.045738  131.709473   43.797543   532.338440
...                ...         ...         ...          ...
2019-09-09  214.169998  142.600006  137.520004  1204.410034
2019-09-10  216.699997  145.050003  136.080002  1206.000000
2019-09-11  223.589996  143.600006  136.119995  1220.170044
2019-09-12  223.089996  143.619995  137.520004  1234.250000
2019-09-13  218.750000  143.669998  137.320007  1239.560059
2019-09-16  219.899994  142.479996  136.330002  1231.300049
2019-09-17  220.699997  142.199997  137.389999  1229.150024
2019-09-18  222.770004  142.220001  138.520004  1232.410034
2019-09-19  220.960007  142.970001  141.070007  1238.709961
2019-09-20  217.729996  141.880005  139.440002  1229.930054
2019-09-23  218.720001  142.070007  139.139999  1234.030029
2019-09-24  217.679993  141.679993  137.380005  1218.760010
2019-09-25  221.029999  143.160004  139.360001  1246.520020
2019-09-26  219.889999  143.550003  139.539993  1241.390015
2019-09-27  218.820007  143.240005  137.729996  1225.089966
2019-09-30  223.970001  145.419998  139.029999  1219.000000
2019-10-01  224.589996  143.660004  137.070007  1205.099976
2019-10-02  218.960007  141.690002  134.649994  1176.630005
2019-10-03  220.820007  142.020004  136.279999  1187.829956
2019-10-04  227.009995  142.990005  138.119995  1209.000000
2019-10-07  227.059998  141.279999  137.119995  1207.680054
2019-10-08  224.399994  138.380005  135.669998  1189.130005
2019-10-09  227.029999  139.669998  138.240005  1202.310059
2019-10-10  230.089996  141.130005  139.100006  1208.670044
2019-10-11  236.210007  142.759995  139.679993  1215.449951
2019-10-14  235.869995  142.039993  139.550003  1217.140015
2019-10-15  235.320007  143.000000  141.570007  1243.010010
2019-10-16  234.369995  142.110001  140.410004  1243.640015
2019-10-17  235.279999  134.259995  139.690002  1253.069946
2019-10-18  236.410004  134.089996  137.410004  1245.489990

[1259 rows x 4 columns]

In [78]:
volume = pd.DataFrame({ticker: data['Volume']
for ticker, data in all_data.items()})

In [79]:
volume

AAPL         IBM        MSFT       GOOG
Date                                                     
2014-10-20  77517300.0  23416500.0  34527900.0  2607500.0
2014-10-21  94623900.0  20949800.0  36433800.0  2336200.0
2014-10-22  68263100.0  11084800.0  33570900.0  2919200.0
2014-10-23  71074700.0   7599400.0  45451900.0  2348800.0
2014-10-24  47053900.0   6652100.0  61076700.0  1973100.0
2014-10-27  34187700.0   4989100.0  30371300.0  1185300.0
2014-10-28  48060900.0   7895300.0  29049800.0  1270900.0
2014-10-29  52687900.0   4739300.0  30276100.0  1770500.0
2014-10-30  40654800.0   3896000.0  30073900.0  1455600.0
2014-10-31  44639300.0   5818000.0  35849700.0  2035000.0
2014-11-03  52282600.0   4688200.0  23130400.0  1382200.0
2014-11-04  41574400.0   4246900.0  21530800.0  1244200.0
2014-11-05  37435900.0   4104700.0  22449600.0  2032200.0
2014-11-06  34968500.0   4067600.0  33037800.0  1333200.0
2014-11-07  33691500.0   3494800.0  28000600.0  1633700.0
2014-11-10  27195500.0   4958200.0  36370100.0  1134600.0
2014-11-11  27442300.0   3534400.0  23445200.0   965500.0
2014-11-12  46942400.0   3378200.0  22722100.0  1129600.0
2014-11-13  59522900.0   3239700.0  26210400.0  1339300.0
2014-11-14  44063600.0   4978400.0  29081700.0  1289500.0
2014-11-17  46746700.0   4798900.0  30318600.0  1726000.0
2014-11-18  44224000.0   5410100.0  23995500.0  1962600.0
2014-11-19  41869200.0   3802600.0  26177500.0  1392200.0
2014-11-20  43395500.0   4183100.0  21510600.0  1563300.0
2014-11-21  57179300.0   4076900.0  42884800.0  2224200.0
2014-11-24  47450800.0   6619000.0  35434200.0  1706300.0
2014-11-25  68840400.0   4062400.0  28008000.0  1789900.0
2014-11-26  40768300.0   3966000.0  27163600.0  1522900.0
2014-11-28  24814400.0   2405500.0  21534400.0  1148300.0
2014-12-01  83814000.0   4168400.0  31191600.0  2115300.0
...                ...         ...         ...        ...
2019-09-09  27309400.0   4226600.0  25773900.0  1471900.0
2019-09-10  31777900.0   4979700.0  28903400.0  1260100.0
2019-09-11  44289600.0   3869700.0  24726100.0  1307000.0
2019-09-12  32226700.0   2505400.0  27010000.0  1725900.0
2019-09-13  39763300.0   2206600.0  23363100.0  1301400.0
2019-09-16  21158100.0   1928500.0  16731400.0  1053300.0
2019-09-17  18318700.0   2933200.0  17814200.0   955100.0
2019-09-18  25340000.0   1983600.0  23982100.0  1135100.0
2019-09-19  22060600.0   3089900.0  35772100.0   996000.0
2019-09-20  55413100.0   5193400.0  39167300.0  2270000.0
2019-09-23  19165500.0   1817900.0  17139300.0  1062400.0
2019-09-24  31190800.0   3231600.0  29773200.0  1583200.0
2019-09-25  21903400.0   2526700.0  21382000.0  1453000.0
2019-09-26  18833500.0   2309800.0  17456600.0  1538000.0
2019-09-27  25352000.0   2356800.0  22477700.0  1353900.0
2019-09-30  25977400.0   3988400.0  17280900.0  1404100.0
2019-10-01  34805800.0   2960800.0  21466600.0  1273500.0
2019-10-02  34612300.0   3340800.0  30521700.0  1615100.0
2019-10-03  28606500.0   2928800.0  24132900.0  1621200.0
2019-10-04  34619700.0   2413600.0  22897700.0  1162400.0
2019-10-07  30576500.0   2426500.0  15303700.0   842900.0
2019-10-08  27955000.0   3225400.0  25550500.0  1039300.0
2019-10-09  18692600.0   2620800.0  19749900.0   867700.0
2019-10-10  28253400.0   2593700.0  17654600.0   846600.0
2019-10-11  41698900.0   2996800.0  25446000.0  1272700.0
2019-10-14  24106900.0   2309500.0  13304300.0   867500.0
2019-10-15  21840000.0   3025500.0  19695700.0  1381700.0
2019-10-16  18475800.0   5332600.0  20751600.0  1094600.0
2019-10-17  16896300.0  15759800.0  21460600.0   952400.0
2019-10-18  24358400.0   7177500.0  32273500.0  1352800.0

[1259 rows x 4 columns]